spring.application.name=component-service
server.port=8083

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/component_db
spring.datasource.username=seu_user
spring.datasource.password=seu_pass

# KAFKA
spring.kafka.consumer.group-id=component-group
app.kafka.topic.in=industria-carro
app.kafka.topic.out=industria-carro
# Mapeamento para garantir que ele entenda o BaseEvent de outros pacotes
spring.kafka.consumer.properties.spring.json.type.mapping=base_event:com.projeto.componentservice.dto.BaseEvent

