spring.application.name=component-service
server.port=8083

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/component_db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# KAFKA
app.kafka.topic=industria-carro

# 1. Forçar o uso do Deserializer de JSON
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# 2. Configurar o pacote confiável
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# 3. Remover os cabeçalhos de tipo que causam conflito entre microsserviços
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# 4. Definir a classe de destino padrão para o payload
spring.kafka.consumer.properties.spring.json.value.default.type=com.projeto.componentservice.dto.BaseEvent
